### ISSUE TITLE
Cannot Grab Nested Variable chain inside print('${}')

### ISSUE THREAD

**Issue by hardiklakhalani** [ricardoemerson/flutter-print#1]
_OS: Windows10_

![image](https://user-images.githubusercontent.com/82162165/145530631-f8387ace-303c-4567-9cd5-31894084e150.png)

instead of `"${store.ingredientList.data}"` it gets as a string

![image](https://user-images.githubusercontent.com/82162165/145530680-0654e04c-5c18-4b66-b9ce-f338437e1c05.png)

**Comment by ricardoemerson** [comment]
Hi, this extension just consider the selected value and not all the context wich the selected value belongs.

In the first case, its correct. You select only the word data and de print was performed using the selected value.
In the second case to print the property of an object you must use [Win] + [Shift] + [L]

You can read better on documentation of the extension:
https://marketplace.visualstudio.com/items?itemName=ricardo-emerson.flutter-print
